#!/bin/sh
# Git Commit Check (gitcc)
# Version: 0.5.0
# Github repo: https://github.com/angtheod/git-commit-check
# Author: Angelos Theodorakopoulos <angtheod@gmail.com>

# Change to the directory of the script and source the required scripts.
cd "$(dirname "$0")" || exit 1
. ./config.sh
cd "$(dirname "$0")" || exit 1
. ./lib.sh

init() {
    START=$(date +%s)
    HAS_ERRORS=0
    HAS_SYNTAX_ERRORS=0
}

header() {
    line3 "╔" "╗" $((WIDTH+8)) "═"
    printf "  %s${CYAN}Load\n" "$SECTION_SYMBOL"
    line "Configuration" "${1:-./config.sh}"
}

check() {
    [ -n "$ENABLED" ] && printf "\n  %s${CYAN}Check${NC}\n" "$SECTION_SYMBOL"

    for script in $(find "$GITCC_SCRIPTS_PATH" -type f -name '*.sh' | sort); do
        _name=$(basename "$script")
        _id="${_name%%_*}"

        # Check if the script is enabled in the configuration and then source the script
        # so that it runs in the same shell process and the variables are accessible within it.
        if contains_string "$_id" "$ENABLED"; then
            before_run_check "$script"
            run_check
            after_run_check
        fi
    done
}

before_run_check() {
    if [ $# -eq 0 ]; then
        printf "(Unknown)\n"
        return 1
    fi

    script=$1

    # Initialise variables.
    HEADER=""
    COMMAND_NAME=""
    COMMAND_VERSION=""

    unset -f after_run # Clear the 'after_run' shell function before sourcing the script.

    . "$script"

    before_run # Call user's before run function.

    line2 "$HEADER" "$LOAD_SYMBOL"
}

run_check() {
    run
}

after_run_check() {
    if [ "$COMMAND_NAME" != "" ] && [ "$COMMAND_VERSION" != "" ]; then
        add_about_info "$COMMAND_NAME" "$COMMAND_VERSION"
    fi

    if type after_run > /dev/null 2>&1; then # Call the function 'after_run' only if the script implements it.
        after_run
    fi
}

about() {
    if [ "$SHOW_ABOUT" = 0 ] || [ -z "$ABOUT" ]; then
        return
    fi

    printf "\n  %s${CYAN}About\n" "$SECTION_SYMBOL"

    split_about_info | while IFS='|' read -r left right; do
        line "$left" "$(extract_version "$right")"
    done
}

footer() {
    line3 "╚" "╝" $((WIDTH+8)) "═"

    END=$(date +%s)
    time=$((END-START))

    if [ "$SHOW_LOG_URL" -eq 1 ]; then
        line3 "$LOG_SYMBOL $LOG_URL" "$TIME_SYMBOL ${time}sec" "$((WIDTH+7))" " "
    else
        line3 "" "$TIME_SYMBOL ${time}sec" "$((WIDTH+7))" " "
    fi
}

main() {
    init
    header
    check
    about
    footer

    if [ "$HAS_ERRORS" -ne 0 ]; then
        exit 1
    fi
}

main

exit $?
