#!/bin/sh
# [Initialise] TODO - 1. Implement function 'before_run'. Fill in the values for the following variables.
before_run() {
  HEADER="MY HEADER"
  COMMAND="my_command"
  COMMAND_NAME="My Command"
  COMMAND_VERSION="$(my_command --version)"
}

# [Execute] # TODO - 2. Implement function 'run'. Add script's custom logic here.
run() {
  # ...

  # TODO - 3. Pass the command output to a variable and if not successful call the 'fail' function. Typical use case:
  output=$(${COMMAND} 2>&1)

  exit=$?

  if [ "$exit" -ne 0 ]; then
    fail "$HEADER" "$output"
    return
  fi

  log info "$HEADER" "Pass." # TODO - 4. Optional: Log a success message or the command's successful output.

  pass # TODO - 5. Call the 'pass' function at the end of the script.

  # pass "$HEADER" "Pass." # Alternatively, you may pass 2 arguments
  # to the 'pass' function to show a message and create a log file entry.
}

# [Finalise] TODO - 6. Optional: Implement function 'after_run' to perform post-check actions.
after_run() {
  # For example, you may call the add_about_info function multiple times to print multiple lines in the about section.
  add_about_info "command2 name" "$(command2 --version)"
}
